name: action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: go-canvas
      DB_USER: root
    
    steps:
      - name: "Mysql Setup"
        run : |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }}

      - name: "Checkout Code"
        uses: actions/checkout@v2
      
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: "Test"
        run: go test -v ./tests

      - name: "Build"
        run: go build -o ./bin/myapp server.go

      - name: "Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: bin/myapp
