name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run golint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint 
        golint -set_exit_status github.com/up1/demo-go-actions/demo
