name: Forest CI
env:
  MYSQL_DATABASE: test_forest
  MYSQL_USER: test_user
  MYSQL_PASSWORD: password
  MYSQL_HOST: mysql-master
  NODE_ENV: test
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
    services:
      mysql-master:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: "npm ci"
      - name: Setup Database
        run: "npm run migrations"
      - name: Run Tests
        run: "npm run test"
